import Head from 'next/head'
import { CldImage } from 'next-cloudinary'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Cloudinary with NextJs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <p>Cloudinary with NextJs</p>
        <CldImage 
          src='v1674306686/nimbus_media/images/slide3.png'
          alt='cloudnary-image' 
          width={500}
          height={500}
          crop='thumb'
         /> 
         <CldImage 
          src='nimbus_media/images/slide8.png'
          alt='cloudnary-image' 
          width={500}
          height={500}
          crop='thumb'
          sizes='100%'
         /> 
      </main>
    </>
  )
}
