import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Cloudinary with NextJs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <p>Cloudinary with NextJs</p>
        <img 
          src='https://res.cloudinary.com/ddgxwjgov/image/upload/v1674306686/nimbus_media/images/slide3.png'
          alt='cloudnary-image'
         /> 
      </main>
    </>
  )
}
